[package]
name = "handless_gameboard"
version = "0.1.0"
authors = ["Daniel Trnka <daniel.trnka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uinput = "0.1.3"
serial = "0.4.0"

